require( "maplogic/forest_1" )
require( "maplogic/forest_2" )
require( "maplogic/dust_1" )
require( "maplogic/dust_2" )
require( "maplogic/dark_1" )
require( "maplogic/dark_2" )
require( "maplogic/jungle_1" )
require( "maplogic/jungle_2" )
