HeroList = {
    druid = {
        {name = "npc_dota_hero_keeper_of_the_light", available = true, hero_id = 90, class="core"},
        {name = "npc_dota_hero_furion", available = true, hero_id = 53, class="core"},
        {name = "npc_dota_hero_lone_druid", available = true, hero_id = 80, class="core"},
        {name = "npc_dota_hero_treant", available = true, hero_id = 83, class="core"},
        -- {name = "npc_dota_hero_legion_commander", available = true, hero_id = 104, class="core"},
    },
    nekro = {
        {name = "npc_dota_hero_death_prophet", available = true, hero_id = 43, class="core"},
        {name = "npc_dota_hero_skeleton_king", available = true, hero_id = 42, class="core"},
        {name = "npc_dota_hero_undying", available = true, hero_id = 85, class="core"},
        {name = "npc_dota_hero_necrolyte", available = true, hero_id = 36, class="core"},
        -- {name = "npc_dota_hero_tidehunter", available = true, hero_id = 29, class="core"},
    },
    inferno = {
        {name = "npc_dota_hero_queenofpain", available = true, hero_id = 39, class="core"},
        {name = "npc_dota_hero_nevermore", available = true, hero_id = 11, class="core"},
        {name = "npc_dota_hero_abyssal_underlord", available = true, hero_id = 108, class="core"},
        {name = "npc_dota_hero_visage", available = true, hero_id = 92, class="core"},
        -- {name = "npc_dota_hero_gyrocopter", available = true, hero_id = 72, class="core"},
    },
    gnom = {
        {name = "npc_dota_hero_techies", available = true, hero_id = 105, class="core"},
        {name = "npc_dota_hero_gyrocopter", available = true, hero_id = 72, class="core"},
        {name = "npc_dota_hero_shredder", available = true, hero_id = 98, class="core"},
        {name = "npc_dota_hero_tinker", available = true, hero_id = 34, class="core"},
        -- {name = "npc_dota_hero_phantom_assassin", available = true, hero_id = 44, class="core"},
    },
    zveri = {
        {name = "npc_dota_hero_leshrac", available = true, hero_id = 52, class="core"},
        {name = "npc_dota_hero_monkey_king", available = true, hero_id = 114, class="core"},
        {name = "npc_dota_hero_tusk", available = true, hero_id = 100, class="core"},
        {name = "npc_dota_hero_hoodwink", available = true, hero_id = 123, class="core"},
        -- {name = "npc_dota_hero_enchantress", available = true, hero_id = 58, class="core"},
    },
    troll = {
        {name = "npc_dota_hero_disruptor", available = true, hero_id = 87, class="core"},
        {name = "npc_dota_hero_troll_warlord", available = true, hero_id = 95, class="core"},
        {name = "npc_dota_hero_axe", available = true, hero_id = 2, class="core"},
        {name = "npc_dota_hero_dazzle", available = true, hero_id = 50, class="core"},
        -- {name = "npc_dota_hero_lina", available = true, hero_id = 25, class="core"},
    },
    people = {
        {name = "npc_dota_hero_invoker", available = true, hero_id = 74, class="core"},
        {name = "npc_dota_hero_juggernaut", available = true, hero_id = 8, class="core"},
        {name = "npc_dota_hero_pudge", available = true, hero_id = 14, class="core"},
        {name = "npc_dota_hero_omniknight", available = true, hero_id = 57, class="core"},
        -- {name = "npc_dota_hero_windrunner", available = false, hero_id = 21, class="core"},
    },
    -- angel = {
    --     {name = "npc_dota_hero_lion", available = false, hero_id = 26, class="core"},
    --     {name = "npc_dota_hero_ogre_magi", available = false, hero_id = 84, class="core"},
    --     {name = "npc_dota_hero_pugna", available = false, hero_id = 45, class="core"},
    --     {name = "npc_dota_hero_shadow_shaman", available = false, hero_id = 27, class="core"},
    --     {name = "npc_dota_hero_windrunner", available = false, hero_id = 21, class="core"},
    -- },
    -- demon = {
    --     {name = "npc_dota_hero_zuus", available = false, hero_id = 22, class="core"},
    --     {name = "npc_dota_hero_nevermore", available = false, hero_id = 11, class="core"},
    --     {name = "npc_dota_hero_tinker", available = false, hero_id = 34, class="core"},
    --     {name = "npc_dota_hero_treant", available = false, hero_id = 83, class="core"},
    --     {name = "npc_dota_hero_slark", available = false, hero_id = 93, class="core"},
    -- },
    -- assasin = {
    --     {name = "npc_dota_hero_wisp", available = false, hero_id = 91, class="core"},
    --     {name = "npc_dota_hero_skywrath_mage", available = false, hero_id = 101, class="core"},
    --     {name = "npc_dota_hero_tusk", available = false, hero_id = 100, class="core"},
    --     {name = "npc_dota_hero_abaddon", available = false, hero_id = 102, class="core"},
    --     {name = "npc_dota_hero_lich", available = false, hero_id = 31, class="core"},
    -- },
}
-- require("AbilitiesLocalize/Utils")